name: read go.mod
description: Reads go.mod

outputs:
  json:
    description: JSON representation of go.mod
    value: ${{ steps.go-mod.outputs.json }}

runs:
  using: "composite"
  steps:
    - id: go-mod
      run: |
        eof="EOF$RANDOM"
        if [[ -f go.mod ]]; then
          {
            echo "json<<$eof";
            go mod edit -json;
            echo "$eof";
          } | tee -a $GITHUB_OUTPUT
        else
          echo "No go.mod file found in $PWD."
          echo "json={}" | tee -a $GITHUB_OUTPUT
        fi
      shell: bash
