name: read config
description: Reads workflow config

outputs:
  json:
    description: JSON config
    value: ${{ steps.config.outputs.json }}

runs:
  using: "composite"
  steps:
    - id: config
      run: |
        eof="EOF$RANDOM"
        path="${GITHUB_WORKFLOW_REF%.yml@*}"
        path="./${path#*/*/}-config.json"
        if [[ -f "$path" ]]; then
          {
            echo "json<<$eof";
            cat "$path";
            echo "$eof";
          } | tee -a "$GITHUB_OUTPUT"
        else
          echo "No config file found at $path"
          echo "json={}" | tee -a "$GITHUB_OUTPUT"
        fi
      shell: bash
