name: Delete Templates

on:
  workflow_dispatch:
    inputs:
      targets:
        description: "List of repository names to deploy to"
        required: true
      files:
        description: "List of files to delete"
        required: true

jobs:
  delete-templates:
    uses: ./.github/workflows/process.yml
    secrets: inherit
    with:
      targets: ${{ github.event.inputs.targets }}
      branch: ucibot/delete-templates
      script: delete-templates.sh
      override: |
        {
          "files": ${{ github.event.inputs.files }}
        }
