name: Delete Templates

on:
  workflow_dispatch:
    inputs:
      targets:
        description: "List of repository names to deploy to"
        required: true
      files:
        description: "List of files to delete"
        required: true
      dry-run:
        description: "Whether to run in dry run mode"
        required: false
        default: 'false'

jobs:
  delete-templates:
    uses: ./.github/workflows/process.yml
    secrets: inherit
    with:
      targets: ${{ github.event.inputs.targets }}
      branch: uci/delete-templates
      script: delete-templates.sh
      override: |
        common:
          files: ${{ github.event.inputs.files }}
      dry-run: ${{ github.event.inputs.dry-run == 'true' }}
