name: Releaser
on:
  workflow_call:
    inputs:
      branches:
        required: false
        type: string
        default: ${{ format('["{0}"]', github.event.repository.default_branch) }}
      sources:
        required: false
        type: string
        default: '["version.json"]'
      separator:
        required: false
        type: string
        default: '/'
      draft:
        required: false
        type: boolean
        default: false
      runner:
        required: false
        type: string
        default: '"ubuntu-latest"'
    outputs:
      json:
        description: JSON aggregation of release.json artifacts
        value: ${{ jobs.aggregate.outputs.json }}
    secrets:
      UCI_GITHUB_TOKEN:
        required: false

jobs:
  releaser:
    runs-on: ${{ fromJSON(vars['UCI_RELEASER_RUNNER'] || inputs['runner']) }}
    strategy:
      fail-fast: false
      matrix:
        source: ${{ fromJSON(inputs.sources) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: version
        name: Determine version
        env:
          SOURCE: ${{ matrix.source }}
          SEPARATOR: ${{ inputs.separator }}
        run: |
          root="$(dirname "$SOURCE")"
          source="$(basename "$SOURCE")"
          echo "root=$root" | tee -a $GITHUB_OUTPUT
          echo "source=$source" | tee -a $GITHUB_OUTPUT
          if [[ "$root" == "." ]]; then
            prefix="v"
          else
            name="$(yq -r '.package.name // .name // "'"$root"'"' "$root/$source")"
            prefix="${name}${SEPARATOR}v"
          fi
          echo "prefix=$prefix" | tee -a $GITHUB_OUTPUT
          while [[ -z "$version" ]]; do
            echo "Checking $root/$source"
            if [[ -f "$root/$source" ]]; then
              version="$(yq -r '.workspace.package.version // .package.version // .version | select(type == "!!str")' "$root/$source")"
              version="${version#v}"
            fi
            if [[ "$root" == "." ]]; then
              break
            fi
            root="$(dirname "$root")"
          done
          echo "version=$version" | tee -a $GITHUB_OUTPUT
          tag="${prefix}${version}"
          echo "tag=$tag" | tee -a $GITHUB_OUTPUT
          suffix="${version#*[-+]}"
          suffix="${suffix#"$version"}"
          echo "suffix=$suffix" | tee -a $GITHUB_OUTPUT
      - id: latest
        if: steps.version.outputs.version != ''
        name: Determine latest version (only final versions)
        env:
          PREFIX: ${{ steps.version.outputs.prefix }}
          TAG: ${{ steps.version.outputs.tag }}
        run: |
          git fetch origin --tags
          echo -e "${TAG}\n$(git tag)" | grep "^${PREFIX}" | grep -v - | sort -V | tail -n1 | xargs -I{} echo "latest={}" | tee -a $GITHUB_OUTPUT
      - id: branch
        name: Check if the branch is a release branch
        if: steps.version.outputs.version != ''
        env:
          BRANCHES: ${{ inputs.branches }}
          REF: ${{ github.ref }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const branches = JSON.parse(process.env.BRANCHES);
            const ref = process.env.REF.replace(/^refs\/heads\//, '');
            const release = branches.some(b => {
              const regexPattern = b.replace(/\*/g, '.*');
              const regex = new RegExp(`^${regexPattern}$`);
              return regex.test(ref);
            });
            console.log(`This is a release branch: ${release}`);
            core.setOutput('release', release);
      - id: pr
        if: steps.version.outputs.version != '' && steps.branch.outputs.release == 'false'
        name: Check if this is a merge commit of a release PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
          SHA: ${{ github.sha }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const [owner, repo] = process.env.REPOSITORY.split('/');
            const ref = process.env.REF.replace(/^refs\/heads\//, '');
            const candidates = await github.paginate(github.rest.pulls.list, {
              owner,
              repo,
              state: 'closed',
              base: ref,
            });
            let pr;
            for (const candidate of candidates) {
              if (candidate.merge_commit_sha === process.env.SHA) {
                pr = candidate;
                break;
              }
            }
            if (pr !== undefined) {
              console.log(`Found PR: ${pr.html_url}`);
              const labels = pr.labels.map(l => l.name);
              const release = labels.includes('release');
              console.log(`This is a release PR: ${release}`);
              core.setOutput('release', release);
            } else {
              console.log('No PR found');
              core.setOutput('release', false);
            }
      - id: tag
        name: Check if tag already exists
        if: steps.branch.outputs.release == 'true' || steps.pr.outputs.release == 'true'
        env:
          TAG: ${{ steps.version.outputs.tag }}
        run: |
          git fetch origin --tags
          status=0
          git rev-list "$TAG" &> /dev/null || status=$?
          if [[ $status == 0 ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - id: release
        name: Create release
        if: steps.tag.outputs.exists == 'false'
        uses: galargh/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          draft: ${{ inputs.draft }}
          tag_name: ${{ steps.version.outputs.tag }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
          make_latest: ${{ steps.version.outputs.prefix == 'v' && steps.version.outputs.suffix == '' && steps.version.outputs.tag == steps.latest.outputs.latest }}
          token: ${{ secrets.UCI_GITHUB_TOKEN || github.token }}
      - name: Create release.json
        if: steps.release.outputs.id != ''
        id: json
        env:
          SOURCE: ${{ matrix.source }}
          RELEASE: |
            {
              "draft": ${{ inputs.draft }},
              "version": "${{ steps.version.outputs.tag }}",
              "url": "${{ steps.release.outputs.url }}",
              "id": "${{ steps.release.outputs.id }}",
              "upload_url": "${{ steps.release.outputs.upload_url }}",
              "assets": ${{ steps.release.outputs.assets }},
              "make_latest": ${{ steps.version.outputs.prefix == 'v' && steps.version.outputs.suffix == '' && steps.version.outputs.tag == steps.latest.outputs.latest }},
              "source": "${{ matrix.source }}"
            }
        run: |
          jq . <<< "$RELEASE" > release.json
          sed 's/[":<>|*?\r\n\\\/]/_/g' <<< "$SOURCE" | xargs -I {} -0 echo "name={}" | tee -a $GITHUB_OUTPUT
      - name: Upload release.json
        if: steps.release.outputs.id != ''
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.json.outputs.name }}
          path: release.json
          overwrite: true
  aggregate:
    needs: [releaser]
    runs-on: ${{ fromJSON(vars['UCI_RELEASER_RUNNER'] || inputs['runner']) }}
    outputs:
      json: ${{ toJSON(fromJSON(steps.aggregate.outputs.json)) }}
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      - id: aggregate
        run: |
          shopt -s globstar
          echo "json<<EOF" >> $GITHUB_OUTPUT
          echo "{" | tee -a $GITHUB_OUTPUT
          for f in **/release.json; do
            if [[ -f "$f" ]]; then
              echo "$comma" | tee -a $GITHUB_OUTPUT
              jq .source "$f" | tee -a $GITHUB_OUTPUT
              echo ":" | tee -a $GITHUB_OUTPUT
              jq . "$f" | tee -a $GITHUB_OUTPUT
              comma=","
            fi
          done
          echo "}" | tee -a $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
