name: Release
on:
  push:
    paths: [CHANGELOG.md]
    branches: [main, release/*]
  pull_request:
    paths: [CHANGELOG.md]
    branches: [main, release/*]
jobs:
  release:
    name: Realase
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: release
        uses: ipdxco/changelog-driven-release@v1
        with:
          path: CHANGELOG.md
          draft: ${{ github.event_name == 'pull_request' }}
      - if: github.event_name == 'pull_request' && steps.release.outputs.tag != ''
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        with:
          header: release
          recreate: true
          message: |
            ## [${{ steps.release.outputs.tag }}](${{ steps.release.outputs.url }})

            ${{ steps.release.outputs.body }}
