name: Release
on:
  push:
    paths: [CHANGELOG.md]
    branches: [main, release/*]
  pull_request:
    paths: [CHANGELOG.md]
    branches: [main, release/*]
jobs:
  release:
    name: Realase
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: release
        uses: ipdxco/changelog-driven-release@1c95572a756629544ca0274ad2348b1181173e01 # v1.0.14
        with:
          path: CHANGELOG.md
          draft: ${{ github.event_name == 'pull_request' }}
      - if: github.event_name == 'pull_request' && steps.release.outputs.tag != ''
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: release
          recreate: true
          message: |
            ## [${{ steps.release.outputs.tag }}](${{ steps.release.outputs.url }})

            ${{ steps.release.outputs.body }}
